# Generated by Django 6.0.6 on 2026-08-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatchInhibitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_batch', models.CharField(max_length=50, unique=True)),
                ('jenis_material', models.CharField(default='ST-37', max_length=50)),
                ('ketebalan', models.FloatField(blank=True, null=True)),
                ('panjang', models.FloatField()),
                ('lebar', models.FloatField()),
                ('jumlah', models.IntegerField()),
                ('total_area_m2', models.FloatField()),
                ('volume_larutan', models.FloatField()),
                ('masa_aman_hari', models.IntegerField()),
                ('tanggal_kadaluarsa', models.CharField(max_length=20)),
                ('dosis_rekomendasi', models.CharField(max_length=20)),
                ('lokasi_gudang', models.CharField(default='Gudang Depok', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
