# Generated by Django 6.0.6 on 2026-08-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_gudang', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('stasiun_bmkg', models.CharField(blank=True, default='', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='batchinhibitor',
            name='jenis_material',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='batchinhibitor',
            name='lokasi_gudang',
            field=models.CharField(max_length=100),
        ),
    ]
